### ISSUE TITLE
make quick-start error

### ISSUE THREAD

**Issue by vastskymiaow** [apache/openwhisk-devtools#291]
Hello,
when I run `make quick-start`, it always tell me that:

Waiting till all containers are powered up... 
Pulling redis (redis:2.8)...
\nIMAGE                                      STATUS
minio/minio:RELEASE.2018-07-13T00-09-07Z   Up 57 seconds (healthy)
\nERROR: Timed out waiting for docker services to launch...
Makefile:279: recipe for target 'wait-for-docker-compose-up' failed
make: *** [wait-for-docker-compose-up] Error 1

It seems that the launch time of docker exceeds the limit, how can i solve it?
I run it in my VM, with the Ubuntu 16.04, 2 vcpu and 8Gb memory. I think it isn't caused by the restrictation of the CPU and memory.

**Comment by nikolavukovic** [comment]
Hello, do you have a solution for this problem?

**Comment by colo76** [comment]
it seems that make failed due to the trycounttimeout timeout,  maybe a 8GB ram is too low for  openwhisk containers. Your processor may affect this I guess

what if after a while... if you run 

$ docker ps

Can you check whether openwhisk containers are running?(even if make has failed).  Try changing this(in the Makefile:)

trycounttimeout=30;  

for a highervalue to check if it works?(and wait)

Good luck!

**Comment by vastskymiaow** [comment]
Thanks. I found it was trycounttimeout that caused the failure. You are true. It has a limitation with my network, so I download the docker image manually. A 8GB ram is truely low for openwhisk.

**Comment by nikolavukovic** [comment]
I am using an Ubuntu 16.04 VM for Openwhisk. I set the memory to 12GB, 2 core vCPU and I also changed trycounttimeout which made this problem disappear. Now I have another problem -> [https://github.com/apache/openwhisk-devtools/issues/292](url)
